# action key
unbind C-b
set -g prefix C-t

# Reload settings
bind r source-file ~/.tmux.conf \; display "Tmux is reloaded!"

unbind '"' # unbind horizontal split
unbind %   # unbind vertical split
bind-key - split-window -v # split pane horizontally
bind-key \ split-window -h # split pane vertically

# List Tmux panes
bind-key Space list-panes

# SetColor Prefix
set -g pane-border-fg green
set -g pane-active-border-fg green

set -g status-bg black
set -g status-fg white

set-option -g status-justify centre

set-option -g status-left '#[bg=black,fg=green][#[fg=cyan]#S#[fg=green]]'
set-option -g status-left-length 20

setw -g automatic-rename on
set-window-option -g window-status-format '#[dim]#I:#[default]#W#[fg=grey,dim]'
set-window-option -g window-status-current-format '#[fg=cyan,bold]#I#[fg=green]:#[fg=cyan]#W#[fg=dim]'

set -g status-right '#[fg=green][#[fg=cyan]%Y-%m-%d#[fg=green]]'
